// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_aHGT1B9xxOfDt1ssHesPL86pQNG4UsA',
    appId: '1:305104906646:web:a46462fd13609fdc0055b7',
    messagingSenderId: '305104906646',
    projectId: 'orbit-54091',
    authDomain: 'orbit-54091.firebaseapp.com',
    storageBucket: 'orbit-54091.appspot.com',
    measurementId: 'G-8ZZLL7CPXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMcUJFkuLDXg1LuXNd42y2he0QHI07VKY',
    appId: '1:305104906646:android:b7edd202b583f6040055b7',
    messagingSenderId: '305104906646',
    projectId: 'orbit-54091',
    storageBucket: 'orbit-54091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWrIxz0NksJSz-LHAAQPasSc71NF1i3Gs',
    appId: '1:305104906646:ios:ae1f3a123069523e0055b7',
    messagingSenderId: '305104906646',
    projectId: 'orbit-54091',
    storageBucket: 'orbit-54091.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWrIxz0NksJSz-LHAAQPasSc71NF1i3Gs',
    appId: '1:305104906646:ios:39d46dba59a7d99a0055b7',
    messagingSenderId: '305104906646',
    projectId: 'orbit-54091',
    storageBucket: 'orbit-54091.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.RunnerTests',
  );
}
